
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class ReturnedDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "所属店铺")]
		public Int32 StoreId { get; set; }

		[Display(Name = "购买会员")]
		public Int32? MemberId { get; set; }

		[Display(Name = "退货单号")]
		public String ReturnedNumber { get; set; }

		[Display(Name = "订单号码")]
		public String OrderNumber { get; set; }

		[Display(Name = "退货状态")]
		public Int32 Status { get; set; }

		[Display(Name = "现金退还")]
		public Decimal Cash { get; set; }

		[Display(Name = "刷卡退还")]
		public Decimal Card { get; set; }

		[Display(Name = "消费积分退还")]
		public Decimal ConsumeScore { get; set; }

		[Display(Name = "获得积分退还")]
		public Decimal AchieveScore { get; set; }

		[Display(Name = "储值退还")]
		public Decimal Balance { get; set; }

		[Display(Name = "抹去退还")]
		public Decimal Coupon { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
