
//   This file was generated by T4 code generator Contract_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using AutoMapper;
using Whiskey.Core;
using Whiskey.Core.Data;
using Whiskey.Web.Helper;
using Whiskey.Web.SignalR;
using Whiskey.Web.Extensions;
using Whiskey.Utility;
using Whiskey.Utility.Data;
using Whiskey.Utility.Web;
using Whiskey.Utility.Class;
using Whiskey.Utility.Extensions;
using Whiskey.ZeroStore.ERP.Transfers;
using Whiskey.ZeroStore.ERP.Models;
using Whiskey.ZeroStore.ERP.Services.Contracts;

namespace Whiskey.ZeroStore.ERP.Services.Contracts
{
    /// <summary>
    /// 服务合约
    /// </summary>
    public interface IPurchaseItemContract : IDependency
    {
        #region PurchaseItem

		PurchaseItem View(int Id);

		PurchaseItemDto Edit(int Id);

        IQueryable<PurchaseItem> PurchaseItems { get; }

		OperationResult Insert(params PurchaseItemDto[] dtos);
        OperationResult Insert(params PurchaseItem[] entities);


        OperationResult Update(params PurchaseItemDto[] dtos);
        OperationResult Update(params PurchaseItem[] entities);


        OperationResult Remove(params int[] ids);

		OperationResult Recovery(params int[] ids);

        OperationResult Delete(params int[] ids);

		OperationResult Enable(params int[] ids);

		OperationResult Disable(params int[] ids);

        bool CheckExists(Expression<Func<PurchaseItem, bool>> predicate, int id = 0);

        #endregion

        OperationResult Insert(params PurchaseItemProduct[] pro);


        OperationResult Insert( PurchaseItemProduct[] purchaseItemProduct,  Inventory[] inventory);
    }
}
