
//   This file was generated by T4 code generator Contract_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using AutoMapper;
using Whiskey.Core;
using Whiskey.Core.Data;
using Whiskey.Web.Helper;
using Whiskey.Web.SignalR;
using Whiskey.Web.Extensions;
using Whiskey.Utility;
using Whiskey.Utility.Data;
using Whiskey.Utility.Web;
using Whiskey.Utility.Class;
using Whiskey.Utility.Extensions;
using Whiskey.ZeroStore.ERP.Transfers;
using Whiskey.ZeroStore.ERP.Models;
using Whiskey.ZeroStore.ERP.Services.Contracts;
using System.Data.Entity;
using Whiskey.ZeroStore.ERP.Models.DTO;

namespace Whiskey.ZeroStore.ERP.Services.Contracts
{
    /// <summary>
    /// 服务合约
    /// </summary>
    public interface IReturnedContract : IDependency
    {
        #region Returned

		Returned View(int Id);

		ReturnedDto Edit(int Id);

        IQueryable<Returned> Returneds { get; }

		OperationResult Insert(params ReturnedDto[] dtos);
        OperationResult Insert(Returned[] retus,bool isTrans);

		OperationResult Update(params ReturnedDto[] dtos);
        OperationResult Update(params Returned[] entity);

        OperationResult Remove(params int[] ids);

		OperationResult Recovery(params int[] ids);

        OperationResult Delete(params int[] ids);

		OperationResult Enable(params int[] ids);

		OperationResult Disable(params int[] ids);

        bool CheckExists(Expression<Func<Returned, bool>> predicate, int id = 0);

        DbContextTransaction GetTransaction();

        OperationResult CanReturn(string retailNumber);
        
        OperationResult AddReturn(ReturnInfoModel resturnInfo);

        /// <summary>
        /// 整单退货商品时计算应退各项金额
        /// </summary>
        OperationResult GetWholyReturnMoney(string retailNumber, string barcodes);
        /// <summary>
        /// 部分退货计算退款金额
        /// </summary>
        OperationResult GetPartialReturnMoney(string retailNumber, string barcodes);

        OperationResult GetRetailBarcodes(string retailNumber);
        /// <summary>
        /// 获取退货金额
        /// </summary>
        /// <param name="retailNumber">退货单</param>
        /// <param name="barcodes">退货流水号</param>
        /// <returns></returns>
        OperationResult GetReturnMoney(string retailNumber, string barcodes);

        #endregion
    }
}
