
//   This file was generated by T4 code generator Contract_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using AutoMapper;
using Whiskey.Core;
using Whiskey.Core.Data;
using Whiskey.Web.Helper;
using Whiskey.Web.SignalR;
using Whiskey.Web.Extensions;
using Whiskey.Utility;
using Whiskey.Utility.Data;
using Whiskey.Utility.Web;
using Whiskey.Utility.Class;
using Whiskey.Utility.Extensions;
using Whiskey.ZeroStore.ERP.Transfers;
using Whiskey.ZeroStore.ERP.Models;
using Whiskey.ZeroStore.ERP.Services.Contracts;

namespace Whiskey.ZeroStore.ERP.Services.Contracts
{
    /// <summary>
    /// 服务合约
    /// </summary>
    public interface ISubjectContract : IDependency
    {
        #region Subject

		Subject View(int Id);

		SubjectDto Edit(int Id);

        IQueryable<Subject> Subjects { get; }

		OperationResult Insert(params SubjectDto[] dtos);

		OperationResult Update(params SubjectDto[] dtos);

		OperationResult Remove(params int[] ids);

		OperationResult Recovery(params int[] ids);

        OperationResult Delete(params int[] ids);

		OperationResult Enable(params int[] ids);

		OperationResult Disable(params int[] ids);

        bool CheckExists(Expression<Func<Subject, bool>> predicate, int id = 0);
        /// <summary>
        /// 添加专题
        /// </summary>
        /// <param name="subject">实体</param>
        /// <param name="listFile">压缩文件集合</param>
        /// <returns></returns>
        OperationResult Insert(Subject subject, HttpFileCollectionBase listFile);
        /// <summary>
        /// 设置首页
        /// </summary>
        /// <param name="Id">主键Id</param>
        /// <returns></returns>
        OperationResult SetHomePage(int Id);

        /// <summary>
        /// 编辑专题
        /// </summary>
        /// <param name="subject">实体</param>
        /// <param name="listFile">压缩文件集合</param>
        /// <returns></returns>
        OperationResult Update(Subject subject, HttpFileCollectionBase listFile);

        #endregion



    }
}
