
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class SubjectDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "专题标题")]
		public String SubjectName { get; set; }

		[Display(Name = "专题内容")]
		public String Description { get; set; }

		[Display(Name = "专题属性")]
        public String Attributes { get; set; }

        [Display(Name = "定义标签")]
        public String Tags { get; set; }

		[Display(Name = "扩展属性")]
        public String Extensions { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
