
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    [Serializable]
    public class MessagerDto : IAddDto, IEditDto<int>
    {

        [Display(Name = "发送人")]
        public virtual int SenderId { get; set; }

        [Display(Name = "接收人")]
        public virtual int ReceiverId { get; set; }

        [Display(Name = "接收人")]
        [Required(ErrorMessage="请选择接受人")]
        public virtual List<int> ReceiverIds { get; set; }

        [Display(Name = "消息标题")]
        [StringLength(100, ErrorMessage = "消息标题不能超过{1}个字符")]
        [Required(ErrorMessage = "请填写消息标题")]
        public virtual string MessageTitle { get; set; }

        [Display(Name = "消息类型")]
        public virtual int MessageType { get; set; }

        [Display(Name = "消息内容")]
        [StringLength(500, ErrorMessage = "消息内容不能超过{1}个字符")]
        [Required(ErrorMessage = "请填写消息内容")]
        public virtual string Description { get; set; }

        [Display(Name = "消息状态")]
        public virtual int Status { get; set; }

        [Display(Name = "标识Id")]
        public virtual int Id { get; set; }

        
    }
}
