
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;
using Whiskey.Utility.Extensions;
using Whiskey.ZeroStore.ERP.Transfers.Enum.Notices;
using Whiskey.ZeroStore.ERP.Models;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class NotificationDto : IAddDto, IEditDto<int>
    {
        public NotificationDto()
        {
            DepartmentIds = new List<int>();
            AdministratorIds = new List<int>();
        }
        [Display(Name = "通知标题")]
        [Required(ErrorMessage = "请填写标题")]
        [StringLength(50, ErrorMessage = "最大长度不能超过{1}个字符")]
        public virtual string Title { get; set; }

        [Display(Name = "通知内容")]
        [Required(ErrorMessage = "请填写内容")]
        //[StringLength(500, ErrorMessage = "最大长度不能超过{1}个字符")]
        public virtual string Description { get; set; }

        [Display(Name = "App推送")]
        public virtual bool IsEnableApp { get; set; }

        [Display(Name = "通知类型")]
        public virtual NoticeFlag NoticeType { get; set; }

        [Display(Name = "发送时间")]
        public virtual DateTime? SendTime { get; set; }

        [Display(Name = "小时")]
        public virtual int Hour { get; set; }

        [Display(Name = "分钟")]
        public virtual int Minute { get; set; }

        [Display(Name = "是否成功")]
        public virtual bool IsSuccessed { get; set; }

        [Display(Name = "通知目标")]
        public virtual int NoticeTargetType { get; set; }

        [Display(Name = "实体标识")]
        public Int32 Id { get; set; }

        [Display(Name = "部门id")]
        public ICollection<int> DepartmentIds { get; set; }
        public ICollection<int> AdministratorIds { get; set; }
        public ICollection<MsgNotificationReader> PushNotifications { get; set; }

        public int? ExamId { get; set; }

        public int? BlogId { get; set; }

        /// <summary>
        /// 是否为入职培训
        /// </summary>
        [Display(Name = "是否为入职培训")]
        [System.ComponentModel.DefaultValue(false)]
        public bool IsEntryTrain { get; set; }
    }
}
