
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class InventoryDto : IAddDto, IEditDto<int>
    {
        [Display(Name = "所属店铺")]
        public Int32 StoreId { get; set; }

        [Display(Name = "所属仓库")]
        public Int32 StorageId { get; set; }

        [Display(Name = "所属商品")]
        public Int32 ProductId { get; set; }

        [Display(Name = "库存数量")]
        public Int32 Quantity { get; set; }
        [Display(Name = "是否锁定库存")]
        public bool IsLock { get; set; }         

        [Display(Name = "吊牌价格")]
        public Decimal TagPrice { get; set; }         

        [Display(Name = "库位编码")]
        public String LocationCode { get; set; }

        [Display(Name = "实体标识")]
        public Int32 Id { get; set; }

        [Display(Name = "排序序号")]
        public Int32 Sequence { get; set; }
        [Display(Name = "入库备注")]
        public virtual string Description { get; set; }

        public int? InventoryRecordId { get; set; }

    }
}
