
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;
using System.ComponentModel;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class PurchaseItemDto : IAddDto, IEditDto<int>
    {
        [Display(Name = "所属商品")]
        public virtual int? ProductId { get; set; }

        [Display(Name = "所属采购单")]
        public virtual int? PurchaseId { get; set; }

        [Display(Name = "吊牌价格")]
        public virtual float TagPrice { get; set; }

        [Display(Name = "批发价格")]
        public virtual float WholesalePrice { get; set; }

        [Display(Name = "采购价格")]
        public virtual float PurchasePrice { get; set; }

        [Display(Name = "采购数量")]
        public virtual int Quantity { get; set; }

        [Display(Name = "是否编辑")]
        [Description("在审核采购单时，该采购信息是否发生了更改")]
        public virtual bool IsEdit { get; set; }

        /// <summary>
        /// 在采购单进行配货时内部调整添加的
        /// </summary>
        [Display(Name = "新添加")]
        public virtual bool IsNewAdded { get; set; }

        [Display(Name = "标识Id")]
        public virtual int Id { get; set; }

    }
}
