
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class SaleItemDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "发货店铺")]
		public Int32 DeliverId { get; set; }

		[Display(Name = "收货店铺")]
		public Int32 ReceiverId { get; set; }

		[Display(Name = "所属商品")]
		public Int32 ProductId { get; set; }

		[Display(Name = "所属销售")]
		public Int32 SaleId { get; set; }

		[Display(Name = "销售单号")]
		public String SaleNumber { get; set; }

		[Display(Name = "吊牌价格")]
		public Decimal TagPrice { get; set; }

		[Display(Name = "零售价格")]
		public Decimal RetailPrice { get; set; }

		[Display(Name = "批发价格")]
		public Decimal WholesalePrice { get; set; }

		[Display(Name = "采购价格")]
		public Decimal PurchasePrice { get; set; }

		[Display(Name = "销售数量")]
		public Int32 Quantity { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
