
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class StorageDto : IAddDto, IEditDto<int>
    {
        [Display(Name = "所属店铺")]
        public Int32 StoreId { get; set; }
        /// <summary>
        /// //0:线上，1:线下
        /// </summary>
        [Display(Name = "仓库类型")]
        public Int32 StorageType { get; set; }
        /// <summary>
        /// 0：可零售商品仓库  1：设备仓库(不可零售商品)
        /// </summary>
        [Display(Name = "仓库种类")]
        public virtual int StorageCategory { get; set; }

        [Display(Name = "仓库名称")]
        [Required(ErrorMessage = "不能为空")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
        public String StorageName { get; set; }

        [Display(Name = "联系电话")]
        [Required(ErrorMessage = "不能为空")]
        public virtual string TelePhone { get; set; }
        [Display(Name = "仓库地址")]
        [Required(ErrorMessage = "不能为空")]
        public virtual string StorageAddress { get; set; }

        [Display(Name = "作为会员归属库")]
        public virtual bool IsVestIn { get; set; }
        [Display(Name = "作为订购库")]
        public virtual bool IsOrderStorage { get; set; }
        [Display(Name = "作为临时仓库")]
        public virtual bool IsTempStorage { get; set; }
        [Display(Name = "作为默认仓库")]
        public virtual bool IsDefaultStorage { get; set; }

        [Display(Name = "统计信息公开")]
        public virtual bool IsPublicInfo { get; set; }

        //[Display(Name = "仓库负责人")]
        //public virtual string StorageAdminStr { get; set; }
        [Display(Name = "仓库简介")]
        public String Description { get; set; }

        [Display(Name = "实体标识")]
        public Int32 Id { get; set; }
        [Display(Name = "创建时间")]
        public DateTime CreatedTime { get; set; }
        [Display(Name = "更新时间")]
        public DateTime UpdatedTime { get; set; }

        [Display(Name = "排序序号")]
        public Int32 Sequence { get; set; }

        [Display(Name = "是否已删除")]
        public bool IsDeleted { get; set; }

        [Display(Name = "是否可用")]
        public bool IsEnabled { get; set; }
        [Display(Name = "操作者")]
        public int? OperatorId { get; set; }
        /// <summary>
        /// 盘点锁定
        /// </summary>
        [Display(Name = "盘点锁定")]
        public virtual bool CheckLock { get; set; }

        [Display(Name = "作为入库仓库")]
        public bool IsForAddInventory { get; set; }

    }
}
