
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class GalleryAttributeDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "父级属性")]
		public Int32? ParentId { get; set; }

		[Display(Name = "属性名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String AttributeName { get; set; }

		[Display(Name = "属性描述")]
        [StringLength(120, ErrorMessage = "最大字符长度不能超过{1}")]
		public String Description { get; set; }

        [Display(Name = "图片路径")]
        [StringLength(100, ErrorMessage = "最大字符长度不能超过{1}")]
        public string IconPath { get; set; }

		[Display(Name = "属性层级")]
		public Int32 AttributeLevel { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
