
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;
using Whiskey.ZeroStore.ERP.Models;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class GalleryDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "图片名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String PictureName { get; set; }

        [Display(Name = "图片类型")]
        public int GalleryType { get; set; }

		[Display(Name = "图片描述")]
		public String Description { get; set; }

		[Display(Name = "定义标签")]
		public String Tags { get; set; }

		[Display(Name = "原始图片")]
		public String OriginalPath { get; set; }

		[Display(Name = "缩略图片")]
		public String ThumbnailPath { get; set; }

		[Display(Name = "扩展属性")]
		public String Extensions { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

        [Display(Name = "图片属性")]
        [Required]
        public string Attributes { get; set; }

        [Display(Name = "图片色彩")]
        public string Colours { get; set; }

        [Display(Name = "颜色样式")]
        public string ColoursHtml { get; set; }

        [Required]
        public virtual ICollection<GalleryAttribute> GalleryAttributes { get; set; }
    }
}
