
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class MemberConsumeDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "消费会员")]
		public Int32 MemberId { get; set; }

		[Display(Name = "消费店铺")]
		public Int32 StoreId { get; set; }

		[Display(Name = "消费类型")]
		public Int32 ConsumeType { get; set; }

		[Display(Name = "消费价格")]
		public Decimal Price { get; set; }

		[Display(Name = "消费积分")]
		public Decimal Score { get; set; }

		[Display(Name = "订单信息")]
		public String RelatedOrderNumber { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
