
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;
using Whiskey.ZeroStore.ERP.Transfers.Enum.Member;
using Whiskey.ZeroStore.ERP.Models.Enums;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class MemberDepositDto : IAddDto, IEditDto<int>
    {
        [Display(Name = "充值会员")]
        public Int32 MemberId { get; set; }

        /// <summary>
        /// 充值积分
        /// </summary>
        [Display(Name = "充值积分总额")]
        public virtual decimal Score { get; set; }


        /// <summary>
        /// 充值金额(仅储值,不包含积分)
        /// </summary>
		[Display(Name = "充值金额")]
        public Decimal Price { get; set; }

        [Display(Name = "现金储值")]
        public Decimal Cash { get; set; }

        [Display(Name = "刷卡储值")]
        public Decimal Card { get; set; }

        [Display(Name = "优惠赠送")]
        public Decimal Coupon { get; set; }

        [Display(Name = "备注信息")]
        [StringLength(200)]
        public String Notes { get; set; }

        [Display(Name = "实体标识")]
        public Int32 Id { get; set; }

        [Display(Name = "充值类型")]
        public virtual MemberDepositFlag MemberDepositType { get; set; }

        [Display(Name = "充值场景")]
        public MemberDepositContextEnum? DepositContext { get; set; }

        [Display(Name = "活动类型")]
        public virtual MemberActivityFlag? MemberActivityType { get; set; }

        [Display(Name = "会员活动")]
        public virtual int? MemberActivityId { get; set; }

        [Display(Name = "充值系数")]
        public virtual decimal Quotiety { get; set; }

        [Display(Name = "充值前余额")]
        public virtual decimal BeforeBalance { get; set; }

        [Display(Name = "充值后余额")]
        public virtual decimal AfterBalance { get; set; }

        [Display(Name = "充值前积分")]
        public virtual decimal BeforeScore { get; set; }

        //微信扫码支付充值生成订单标识
        [Display(Name = "订单标识")]
        public virtual string order_Uid { get; set; }

        [Display(Name = "充值后积分")]
        public virtual decimal AfterScore { get; set; }

        [Display(Name = "充值后积分")]
        public virtual decimal TotalPrice { get; set; }


        /// <summary>
        /// 订单信息
        /// </summary>
        [StringLength(100, ErrorMessage = "{0}不能超过100个字符")]
        [Display(Name = "订单信息")]
        public virtual string RelatedOrderNumber { get; set; }


        /// <summary>
        /// 订单类型
        /// </summary>
        [Display(Name = "订单类型")]
        public virtual OrderTypeEnum? OrderType { get; set; }


        /// <summary>
        /// 充值店铺
        /// </summary>
        [Display(Name = "充值店铺")]
        public int? DepositStoreId { get; set; }

    }
}
