
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class MemberGiftDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "兑换会员")]
		public Int32 MemberId { get; set; }

		[Display(Name = "兑换店铺")]
		public Int32 StoreId { get; set; }

		[Display(Name = "消耗积分")]
		public Int32 Score { get; set; }

		[Display(Name = "备注信息")]
		public String Notes { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
