
//   This file was generated by T4 code generator Configuration_Creator.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Whiskey.Core.Data.Entity;
using Whiskey.ZeroStore.ERP.Models;

namespace Whiskey.ZeroStore.ERP.Models
{
    /// <summary>
    /// 实体配置
    /// </summary>
    public class ArticleAttributeConfiguration : EntityConfigurationBase<ArticleAttribute, int>
    {
        public ArticleAttributeConfiguration()
        {
            ToTable("P_Article_Attribute");
			Property(m => m.Id).HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
        }
    }
}
