
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class DiscountDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String DiscountName { get; set; }

		[Display(Name = "打折类型")]
		public Int32 DiscountMethod { get; set; }

		[Display(Name = "折扣简介")]
		public String Description { get; set; }

		[Display(Name = "开始时间")]
		public DateTime StartTime { get; set; }

		[Display(Name = "结束时间")]
		public DateTime EndTime { get; set; }

		[Display(Name = "按订单金额打折")]
		public Boolean DiscountByPrice { get; set; }

		[Display(Name = "订单金额满")]
		public Decimal DiscountPrice { get; set; }

		[Display(Name = "按货品数量打折")]
		public Boolean DiscountByAmount { get; set; }

		[Display(Name = "货品数量满")]
		public Decimal DiscountAmount { get; set; }

		[Display(Name = "折扣类型")]
		public Int32 DiscountType { get; set; }

		[Display(Name = "折扣比例")]
		public Decimal DiscountRate { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
