
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class PaymentDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "支付名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String PaymentName { get; set; }

		[Display(Name = "支付商家ID")]
		public String PaymentPartner { get; set; }

		[Display(Name = "支付密钥")]
		public String PaymentKey { get; set; }

		[Display(Name = "手续费用")]
		public Decimal PaymentFee { get; set; }

		[Display(Name = "联系电话")]
		public String MobilePhone { get; set; }

		[Display(Name = "公司网站")]
		public String Website { get; set; }

		[Display(Name = "备注信息")]
		public String Notes { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
