
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class TimeoutSettingDto : IAddDto, IEditDto<int>
    {
        public int Id { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        [Display(Name = "名称")]
        public string Name { get; set; }

        /// <summary>
        /// 描述
        /// </summary>
        [Display(Name = "描述")]
        public string Desc { get; set; }

        /// <summary>
        /// 超时时间
        /// </summary>
        [Display(Name = "超时时间(单位:秒)")]

        public int TimeSpan { get; set; }

        /// <summary>
        /// 扣除积分
        /// </summary>
        [Display(Name = "扣除积分")]
        public int DeductScore { get; set; }
    }
}
