
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class BrandDto : IAddDto, IEditDto<int>
    {
        public BrandDto()
        {
            IsDeleted = false;
            IsEnabled = true;
        }
        [Display(Name = "父级品牌")]
        public Int32? ParentId { get; set; }

        [Display(Name = "品牌名称")]
        [Required(ErrorMessage = "不能为空")]
        [StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
        public String BrandName { get; set; }

        [Display(Name = "品牌图标")]
        [StringLength(100)]
        public string IconPath { get; set; }

        [Display(Name = "品牌编码")]
        [StringLength(4)]
        public string BrandCode { get; set; }

        [Display(Name = "品牌描述")]
        public String Description { get; set; }
        [Display(Name = "品牌故事")]
        public virtual string BrandStory { get; set; }
        [Display(Name = "实体标识")]
        public Int32 Id { get; set; }

        [Display(Name = "默认折扣")]
        [Required(ErrorMessage = "默认折扣不为空")]
        [Range(0.000001, 1, ErrorMessage = "折扣范围在0.000001~~1之间")]
        public virtual double DefaultDiscount { get; set; }

        [Display(Name = "排序序号")]
        public Int32 Sequence { get; set; }
        public bool IsDeleted { get; set; }
        [Display(Name="是否启用")]
        public bool IsEnabled { get; set; }

    }
}
