
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class CategoryDto : IAddDto, IEditDto<int>
    {
        public CategoryDto()
        {
            IsDeleted = false;
            IsEnabled = true;
        }

		[Display(Name = "父级分类")]
		public Int32? ParentId { get; set; }

		[Display(Name = "分类名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(10, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
        public string CategoryName { get; set; }

        [Display(Name = "分类编码")]
        [StringLength(2, ErrorMessage = "{0}1~2个字符！")]
        [Required(ErrorMessage = "编码不能为空！")]
        [RegularExpression(@"[A-Za-z0-9]+", ErrorMessage = "编码必须是数字或者字母")]
        public string CategoryCode { get; set; }		 

		[Display(Name = "分类描述")]
        [StringLength(120)]
        public string Description { get; set; }

        [Display(Name = "显示图")]
        [StringLength(100)]
        public string IconPath { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsEnabled { get; set; }

    }
}
