
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class ColorDto : IAddDto, IEditDto<int>
    {
        public ColorDto()
        {
            IsDeleted = false;
            IsEnabled = true;
        }

		[Display(Name = "父级色彩")]
		public Int32? ParentId { get; set; }

		[Display(Name = "色彩名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(10, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String ColorName { get; set; }

		[Display(Name = "色彩编码")]
        [Required(ErrorMessage="不能为空")]
        [StringLength(2,ErrorMessage = "最多{1}个字符")]
        [RegularExpression(@"[A-Za-z0-9]+", ErrorMessage = "编码必须是数字或者字母")]
        public String ColorCode { get; set; }

        #region 注释字段

        //[Display(Name = "色彩层级")]
        //public Int32 ColorLevel { get; set; }

        //[Display(Name = "色彩描述")]
        //public String Description { get; set; }

        //[Display(Name = "最小色相值")]
        //public Double MinHue { get; set; }

        //[Display(Name = "最大色相值")]
        //public Double MaxHue { get; set; }

        //[Display(Name = "最小饱和度")]
        //public Double MinSaturation { get; set; }

        //[Display(Name = "最大饱和度")]
        //public Double MaxSaturation { get; set; }

        //[Display(Name = "最小明度值")]
        //public Double MinLightness { get; set; }

        //[Display(Name = "最大明度值")]
        //public Double MaxLightness { get; set; }

        //[Display(Name = "RGB")]
        //public String RGB { get; set; }

        //[Display(Name = "HSL")]
        //public String HSL { get; set; }

        #endregion


        [Display(Name = "色值")]
        [StringLength(20)]
        public virtual string ColorValue { get; set; }

        [Display(Name = "色彩描述")]
        [StringLength(120)]
        public string Description { get; set; }

        [Display(Name = "颜色图标")]
        [StringLength(100)]
        public string IconPath { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

        public bool IsDeleted { get; set; }
        public bool IsEnabled { get; set; }
    }
}
