
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;
using Whiskey.ZeroStore.ERP.Models;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class SizeDto : IAddDto, IEditDto<int>
    {
        public SizeDto()
        {
            IsDeleted = false;
            IsEnabled = true;
        }
        [Display(Name = "二级品类")]
        public int CategoryId { get; set; }

        //[Display(Name = "父级尺码")]
        //public Int32? ParentId { get; set; }

		[Display(Name = "尺码名称")]
		[Required(ErrorMessage = "不能为空")]
		[StringLength(50, MinimumLength = 1, ErrorMessage = "至少{2}～{1}个字符")]
		public String SizeName { get; set; }

		[Display(Name = "尺码编码")]
        [Required(ErrorMessage = "不能为空")]
        [StringLength(2, ErrorMessage = "最多{1}个字符")]
        [RegularExpression(@"[A-Za-z0-9]+", ErrorMessage = "编码必须是数字或者字母")]
		public String SizeCode { get; set; }		

		[Display(Name = "尺码描述")]
		public String Description { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

        [Display(Name = "图标")]
        [StringLength(100)]
        public string IconPath { get; set; }

        [Display(Name = "尺码属性")]
        public virtual int? SizeExtentionId { get; set; }
        
		public Int32 Sequence { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsEnabled { get; set; }
    }
}
