
//   This file was generated by T4 code generator Dto_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Text;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Whiskey.Core.Data;

namespace Whiskey.ZeroStore.ERP.Transfers
{
    public class ProductImageDto : IAddDto, IEditDto<int>
    {
		[Display(Name = "商品ID")]
		public Int32? ProductId { get; set; }

		[Display(Name = "原始图片")]
		public String OriginalPath { get; set; }

		[Display(Name = "小缩略图")]
		public String ThumbnailSmallPath { get; set; }

		[Display(Name = "中缩略图")]
		public String ThumbnailMediumPath { get; set; }

		[Display(Name = "大缩略图")]
		public String ThumbnailLargePath { get; set; }

		[Display(Name = "实体标识")]
		public Int32 Id { get; set; }

		[Display(Name = "排序序号")]
		public Int32 Sequence { get; set; }

    }
}
