
//   This file was generated by T4 code generator Contract_Creater.tt.



using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Web;
using AutoMapper;
using Whiskey.Core;
using Whiskey.Core.Data;
using Whiskey.Web.Helper;
using Whiskey.Web.SignalR;
using Whiskey.Web.Extensions;
using Whiskey.Utility;
using Whiskey.Utility.Data;
using Whiskey.Utility.Web;
using Whiskey.Utility.Class;
using Whiskey.Utility.Extensions;
using Whiskey.ZeroStore.ERP.Transfers;
using Whiskey.ZeroStore.ERP.Models;
using Whiskey.ZeroStore.ERP.Services.Contracts;
using System.Web.Mvc;

namespace Whiskey.ZeroStore.ERP.Services.Contracts
{
    /// <summary>
    /// 服务合约
    /// </summary>
    public interface IBrandContract : IDependency
    {
        #region Brand

		Brand View(int Id);

		BrandDto Edit(int Id);

        IQueryable<Brand> Brands { get; }

		OperationResult Insert(params BrandDto[] dtos);

		OperationResult Update(params BrandDto[] dtos);

		OperationResult Remove(params int[] ids);

		OperationResult Recovery(params int[] ids);

        OperationResult Delete(params int[] ids);

		OperationResult Enable(params int[] ids);

		OperationResult Disable(params int[] ids);

        IEnumerable<KeyValue<string, string>> SelectList(string title);
        

        /// <summary>
        /// 获取键值列表
        /// </summary>
        /// <returns></returns>
        IEnumerable<KeyValue<string, string>> SelectList();

        string FullName(int id, int level);

        string FullCode(int id, int level);

        bool CheckExists(Expression<Func<Brand, bool>> predicate, int id = 0);

        IEnumerable<SelectListItem> ParentSelectList(string title);


        #endregion

    }
}
